epicovid/__init__.py
from flask import Flask
from epicovid.config import Config

def create_app():
    """
    create_app

    Create the flask app with every config needed for the website

    :return: Flask Application
    :rtype: Flask App
    """
    app = Flask(__name__)
    app.config.from_object(Config)

    from epicovid.main.routes import main
    app.register_blueprint(main)
    
    return app

epicovid/main/routes.py
from flask import render_template, request, Blueprint
from epicovid.main.data import Data
from datetime import datetime
from epicovid.main.data_adapter import getConfirmedCasesByCountry, getTotalDeathsByCountry, getRecoveredByCountry, getChartsData
import json

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home/')
def home():
    """
    home

    Create a Chart and a Data object and return the home page template with Data object

    :return: render the template with data needed for the charts and the data containers
    :rtype: html template
    """
    dataConf = Data()
    chartsData = getChartsData()
    return render_template('home.html',
                           chartsData=chartsData, data=dataConf)


@main.route('/totalConfirmed/')
def totalConfirmed():
    """
    totalConfirmed

    Create a Data object and return the totalConfirmed page template with Data object

    :return: render the template with data needed for the data containers
    :rtype: html template
    """
    totalConfirmed = Data().getTotalConfirmed()
    return render_template('totalConfirmed.html', totalConfirmed=totalConfirmed)


@main.route('/confirmedCasesByCountry/')
def confirmedCasesByCountry():
    """
    confirmedCasesByCountry

    Create a Data object and return the confirmedCasesByCountry page template with Data object

    :return: render the template with data needed for the data containers
    :rtype: html template
    """
    confirmedCasesByCountry = getConfirmedCasesByCountry()
    return render_template('confirmedCasesByCountry.html', confirmedCasesByCountry=confirmedCasesByCountry)

@main.route('/totalDeaths/')
def totalDeaths():
    """
    totalDeaths

    Create a Data object and return the totalDeaths page template with Data object

    :return: render the template with data needed for the data containers
    :rtype: html template
    """
    totalDeath = Data().getTotalDeath()
    return render_template('totalDeaths.html', totalDeath=totalDeath)

@main.route('/deathsCasesByCountry/')
def deathsCasesByCountry():
    """
    deathsCasesByCountry

    Create a Data object and return the deathsCasesByCountry page template with Data object

    :return: render the template with data needed for the data containers
    :rtype: html template
    """
    deathsCasesByCountry = getTotalDeathsByCountry()
    return render_template('deathsCasesByCountry.html', deathsCasesByCountry=deathsCasesByCountry)

@main.route('/totalRecovered/')
def totalRecovered():
    """
    totalRecovered

    Create a Data object and return the totalRecovered page template with Data object

    :return: render the template with data needed for the data containers
    :rtype: html template
    """
    totalRecovered = Data().getTotalRecovered()
    return render_template('totalRecovered.html', totalRecovered=totalRecovered)

@main.route('/recoveredCasesByCountry/')
def recoveredCasesByCountry():
    """
    recoveredCasesByCountry

    Create a Data object and return the recoveredCasesByCountry page template with Data object

    :return: render the template with data needed for the data containers
    :rtype: html template
    """
    recoveredCasesByCountry = getRecoveredByCountry()
    return render_template('recoveredCasesByCountry.html', recoveredCasesByCountry=recoveredCasesByCountry)

@main.route('/charts/')
def charts():
    """
    charts

    Create a Chart object and return the charts page template with Data object

    :return: render the template with data needed for the data containers
    :rtype: html template
    """
    chartsData = getChartsData()
    return render_template('charts.html', chartsData=chartsData)

@main.route('/map/')
def map():
    """
    map

    Create a Data object and return the map page template with Data object

    :return: render the template with data needed for the data containers
    :rtype: html template
    """
    dataConf = Data()
    return render_template('map.html', data=dataConf)

epicovid/templates/Map.html
<link rel="stylesheet" href="https://js.arcgis.com/4.15/esri/themes/light/main.css">
<script src="https://js.arcgis.com/4.15/"></script>
<title>ArcGIS JavaScript Tutorials: Create a JavaScript starter app</title>
<style>
  html, body, #viewDiv {
    padding: 0;
    margin: 0;
    height: 100%;
    width: 100%;
  }
</style>
<body>
  <div id="viewDiv"></div>
</body>
<script type="text/javascript">
require([
  "esri/Map",
  "esri/views/MapView",
  "esri/Graphic",
  "esri/layers/GraphicsLayer",
  "esri/geometry/Point"
], function(Map, MapView, Graphic, GraphicsLayer) {

  var tab = {{ data.tabConf | tojson }};
  var maxSize = {{ data.max }};
  var minSize = {{ data.min }};

  console.log(minSize)
  console.log(maxSize)
  
  
  var map = new Map({
      basemap: "dark-gray-vector"
  });

  
  var view = new MapView({
      container: "viewDiv",
      map: map,
      center: [0, 0],
      zoom: 2
  });

  var graphicsLayer = new GraphicsLayer();
  
  for (let i = 0; i < tab.length; i++) {

    map.add(graphicsLayer);
    
    var pingSize = tab[i][2] * 40 / maxSize + 3

    var point = {
      type: "point",
      longitude: tab[i][1],
      latitude: tab[i][0]
    };

  var simpleMarkerSymbol = {
    type: "simple-marker",
    color: [230, 14, 14, 0.4],
    size: pingSize,
    "outline": {
      "color": [230, 14, 14, 1],
      "width": 1,
    }
  };

  var pointGraphic = new Graphic({
    geometry: point,
    symbol: simpleMarkerSymbol,
    
  });

  graphicsLayer.add(pointGraphic);
  }
});
</script>

epicovid/templates/charts.html
<ul class="tabs" role="tablist">
    <li>
        <input type="radio" name="tabs" id="tab1" checked />
        <label for="tab1" 
               role="tab" 
               aria-selected="true" 
               aria-controls="panel1" 
               tabindex="0">{{ chartsData.confirmedCases.legend }}</label>
        <div id="tab-content1" 
             class="tab-content" 
             role="tabpanel" 
             aria-labelledby="description" 
             aria-hidden="false">
          <canvas id="myChart1" width="600" height="400"></canvas>
        </div>
    </li>
  
    <li>
        <input type="radio" name="tabs" id="tab2" />
        <label for="tab2"
               role="tab" 
               aria-selected="false" 
               aria-controls="panel2" 
               tabindex="0">{{ chartsData.deathCount.legend }}</label>
        <div id="tab-content2" 
             class="tab-content"
             role="tabpanel" 
             aria-labelledby="specification" 
             aria-hidden="true">
          <canvas id="myChart2" width="600" height="400"></canvas>
        </div>
    </li>

    <li>
        <input type="radio" name="tabs" id="tab3" />
        <label for="tab3"
               role="tab" 
               aria-selected="false" 
               aria-controls="panel3" 
               tabindex="0">{{ chartsData.newCases.legend }}</label>
        <div id="tab-content3" 
             class="tab-content"
             role="tabpanel" 
             aria-labelledby="specification" 
             aria-hidden="true">
          <canvas id="myChart3" width="600" height="400"></canvas>
        </div>
    </li>
</ul>

<script>
    Chart.defaults.global.responsive = false;

    var myOptions = {
        legend: {
            display: false
        },
        scales: {
            yAxes: [{
                ticks: {
                    callback: function(value, index, values) {
                        if (value >= 1e3 && value < 1e6) { return value / 1e3 + 'k'; }
                        else if (value >= 1e6 && value < 1e9) { return value / 1e6 + 'M'; }
                        else { return value; }
                    }
                }
            }],
            xAxes: [{
                type: 'time',
                position: 'bottom',
                time: {
                    displayFormats: {'day': 'MM'},
                    tooltipFormat: 'DD/MM/YY',
                    unit: 'month',
                }
            }],
        }
    };
    
    var ctx = document.getElementById("myChart1").getContext("2d");
    var myChart1 = new Chart(ctx, {
        type: 'scatter',
        data: {
            labels: [
                {% for item in chartsData.confirmedCases.labels %}
                    "{{ item.month }}/{{ item.day }}/{{ item.year }}",
                {% endfor %}],
            datasets: [{
                label: '{{ chartsData.confirmedCases.legend }}',
                data: [
                    {% for item in chartsData.confirmedCases.values %}
                        {{ item }},
                    {% endfor %}
                ],
                pointBackgroundColor: "#fb0"
            }]
        },
        options: myOptions
    });

    var ctx2 = document.getElementById("myChart2").getContext("2d");
    var myChart2 = new Chart(ctx2, {
        type: 'scatter',
        data: {
            labels: [
                {% for item in chartsData.deathCount.labels %}
                    "{{ item.month }}/{{ item.day }}/{{ item.year }}",
                {% endfor %}],
            datasets: [{
                label: '{{ chartsData.deathCount.legend }}',
                data: [
                    {% for item in chartsData.deathCount.values %}
                        {{ item }},
                    {% endfor %}
                ],
                pointBackgroundColor: "#fb0"
            }]
        },
        options: myOptions
    });

    var ctx3 = document.getElementById("myChart3").getContext("2d");
    var myChart3 = new Chart(ctx3, {
        type: 'bar',
        data: {
            labels: [
                {% for item in chartsData.newCases.labels %}
                    "{{ item.month }}/{{ item.day }}/{{ item.year }}",
                {% endfor %}],
            datasets: [{
                label: '{{ chartsData.newCases.legend }}',
                data: [
                    {% for item in chartsData.newCases.values %}
                        {{ item }},
                    {% endfor %}
                ],
                backgroundColor: "#fb0"
            }]
        },
        options: myOptions
    });

</script>

epicovid/templates/confirmedCasesByCountry.html
<div style="font-size: 18px; margin: 20px;">Confirmed cases by country</div>
<ul style="text-align: left; font-size: 18px;">
    {% for item in confirmedCasesByCountry %}
    <li style="border-bottom: 1px solid #363636; padding: 10px 20px 10px 20px;">
        <span style="font-weight: bold; color: red;">{{ "{0:,}".format(item[1]).replace(',', ' ') }}</span>
        <span>{{ item[0] }}</span>
    </li>
    {% endfor %}
</ul>

epicovid/templates/deathsCasesByCountry.html
<ul style="text-align: left; font-size: 18px;">
    {% for item in deathsCasesByCountry %}
    <li style="border-bottom: 1px solid #363636; padding: 10px 20px 10px 20px;">
        <span style="color: #70a800;"><span style="font-weight: bold;">{{ "{0:,}".format(item[1]).replace(',', ' ') }}</span> deaths</span>
        <br/>
        <span>{{ item[0] }}</span>
    </li>
    {% endfor %}
</ul>

epicovid/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>Covid-19 Dashboard</title>
    <link rel="stylesheet" type="text/css" href="static/style.css">
    <link rel="stylesheet" href="https://js.arcgis.com/4.15/esri/themes/light/main.css">
    <link rel="icon" href="{{ url_for('static', filename='favicon.png') }}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js"></script>
    <script src="{{ url_for('static', filename='Chart.min.js') }}"></script>
    <script src="https://js.arcgis.com/4.15/"></script>
</head>

<body>
    <!-- <h1 id="title">Covid-19 Dashboard</h1> -->

    <div class="wrapper">

        <div id="container" class="div1">
            <span style="font-size: 30px;">COVID-19 Dashboard by Souhib</span>
        </div>

        <div class="div2">
          <div id="container">
            <div id="totalConfirmed"></div>
          </div>
          <div id="container">
            <div id="confirmedCasesByCountry" style="height: 635px; overflow-y: auto"></div>
          </div>
        </div>
        
        <div id="container" class="div3">
            <div id="viewDiv"></div>
        </div>

        <div class="div4">
          <div id="container">
            <div id="totalDeath"></div>
          </div>
          <div id="container">
            <div id="deathsCasesByCountry" style="height: 200px; overflow-y: auto"></div>
          </div>
        </div>

        <div class="div5">
          <div id="container">
            <div id="totalRecovered"></div>
          </div>
          <div id="container">
            <div id="recoveredCasesByCountry" style="height: 200px; overflow-y: auto"></div>
          </div>
        </div>

        <div id="container" class="div6" style="height: 550px;">
            <div id="charts"></div>
        </div>

        <div id="container" class="div7">
           <span style="font-size: 150%;">Total Region {{data.region}}</span>
           <br/>
           <br/>
           <span style="font-size: 150%;">Last Updated at ({{data.lastUpdate}})</span>
        </div>
    </div>

</body>

<script>
    $(function(){
        $("#map").load("{{ url_for('main.map') }}");
        $("#totalConfirmed").load("{{ url_for('main.totalConfirmed') }}");
        $("#confirmedCasesByCountry").load("{{ url_for('main.confirmedCasesByCountry') }}");
        $("#totalDeath").load("{{ url_for('main.totalDeaths') }}");
        $("#deathsCasesByCountry").load("{{ url_for('main.deathsCasesByCountry') }}");
        $("#totalRecovered").load("{{ url_for('main.totalRecovered') }}");
        $("#recoveredCasesByCountry").load("{{ url_for('main.recoveredCasesByCountry') }}");
        $("#charts").load("{{ url_for('main.charts') }}");
    });
</script>

<script type="text/javascript">
require([
  "esri/Map",
  "esri/views/MapView",
  "esri/Graphic",
  "esri/layers/GraphicsLayer",
  "esri/geometry/Point"
], function(Map, MapView, Graphic, GraphicsLayer) {

  var tab = {{ data.tabConf | tojson }};
  var maxSize = {{ data.max }};
  var minSize = {{ data.min }};

  console.log(minSize)
  console.log(maxSize)
  
  
  var map = new Map({
      basemap: "dark-gray-vector"
  });

  
  var view = new MapView({
      container: "viewDiv",
      map: map,
      center: [0, 0],
      zoom: 2
  });

  var graphicsLayer = new GraphicsLayer();
  
  for (let i = 0; i < tab.length; i++) {

    map.add(graphicsLayer);
    
    var pingSize = tab[i][2] * 40 / maxSize + 3

    var point = {
      type: "point",
      longitude: tab[i][1],
      latitude: tab[i][0]
    };

  var simpleMarkerSymbol = {
    type: "simple-marker",
    color: [230, 14, 14, 0.4],
    size: pingSize,
    "outline": {
      "color": [230, 14, 14, 1],
      "width": 1,
    }
  };

  var pointGraphic = new Graphic({
    geometry: point,
    symbol: simpleMarkerSymbol,
    
  });

  graphicsLayer.add(pointGraphic);
  }
});
</script>

</html>

epicovid/templates/recoveredCasesByCountry.html
<ul style="text-align: left; font-size: 18px;">
    {% for item in recoveredCasesByCountry %}
    <li style="border-bottom: 1px solid #363636; padding: 10px 20px 10px 20px;">
        <span style="color: #73b2ff;"><span style="font-weight: bold;">{{ "{0:,}".format(item[1]).replace(',', ' ') }}</span> recovered</span>
        <br/>
        <span>{{ item[0] }}</span>
    </li>
    {% endfor %}
</ul>

epicovid/templates/totalConfirmed.html
<div style="padding: 20px;">
    <p style="font-size: 18px;">Total confirmed</p>
    <p id="total" style="font-size: 30px; font-weight: bold; color: red;"></p>
</div>

<script>

    function formatNumber(num) {
        return num.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1 ')
    }
    var number = formatNumber({{ totalConfirmed }});

    var total = document.getElementById("total");
    total.innerText = number;

</script>

epicovid/templates/totalDeaths.html
<div style="padding: 20px;">
    <p style="font-size: 18px;">Total deaths</p>
    <p id="total2" style="font-size: 30px; font-weight: bold; color: #70a800;"></p>
</div>

<script>

    function formatNumber(num) {
        return num.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1 ')
    }
    var number = formatNumber({{ totalDeath }});

    var total2 = document.getElementById("total2");
    total2.innerText = number;

</script>

epicovid/templates/totalRecovered.html
<div style="padding: 20px;">
    <p style="font-size: 18px;">Total recovered</p>
    <p id="total3" style="font-size: 30px; font-weight: bold; color: #73b2ff;"></p>
</div>

<script>

    function formatNumber(num) {
        return num.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1 ')
    }
    var number = formatNumber({{ totalRecovered }});

    var total3 = document.getElementById("total3");
    total3.innerText = number;

</script>